### PR TITLE
Replace "Unix" with "Linux" in about command.

### PR DESCRIPTION
**Pull request by seal331**
Not like anyone will try to run this on macOS, Android or iOS, which probably have their own OS name which is not "Unix".
Adds a getPlatform() function, adapts AboutCommand.cs and adds me to the contributors list.

### CODE REVIEW

**Comment by dkay0670** [comment]
Wat

**Comment by seal331** [comment]
smh dkay stop watting everything

**Comment by floppydisk05** [comment]
what

**Comment by floppydisk05** [comment]
This is the most dumb, pointless shit I've ever seen ngl

**Comment by seal331** [comment]
it triggers me so i did it lol

**Comment by dkay0670** [comment]
Well it's stupid

**Comment by nick99nack** [comment]
173347877-8dc1b2c0-6bfc-4401-aed2-71c180c153f9

**Comment by floppydisk05** [comment]
This is the most dumb, pointless shit I've ever seen ngl

**Comment by seal331** [comment]
no it's not
anyways let's wait for hiden

**Comment by dkay0670** [comment]
Yes, send your message again for no reason

**Comment by floppydisk05** [comment]
> it triggers me so i did it lol

You being somehow personally triggered is not a valid reason to make a pull request.

**Comment by floppydisk05** [comment]
> Yes, send your message again for no reason 

I edited it and GitHub mobile had a stroke

**Comment by floppydisk05** [comment]
> > > it triggers me so i did it lol
> > 
> > You being somehow personally triggered is not a valid reason to make a pull request.
> 
> I asked HIDEN in the corner some time ago and she said that she just doesn't have experience with .NET to change what that function whose name I forgot again, she didn't object explicitly so politely fuck off until HIDEN answers

How am I supposed to know things I can't see lol. Also unnecessarily rude for no reason

**Comment by seal331** [comment]
you're also always rude to gentoo for no reason

**Comment by floppydisk05** [comment]
> you're also always rude to gentoo for no reason

I will just say that that is entirely because of you. Don't try to start drama in a GitHub PR for the love of god

**Comment by floppydisk05** [comment]
> > > you're also always rude to gentoo for no reason
> > 
> > I will just say that that is entirely because of you. Don't try to start drama in a GitHub PR for the love of god
> 
> You're the one starting drama, not me, and I have no idea how you convinced tox it's me making drama a few months ago

says the one dragging my dislike of Gentoo into a conversation about C#

**Comment by HIDEN64** [comment]
> > > it triggers me so i did it lol
> > 
> > 
> > You being somehow personally triggered is not a valid reason to make a pull request.
> 
> I asked HIDEN in the corner some time ago and she said that she just doesn't have experience with .NET to change what that function whose name I forgot again outputs, she didn't object explicitly so politely fuck off until HIDEN answers

I meant the literal .NET source code from Microsoft.

**Comment by HIDEN64** [comment]
Anyway, this is pointless + it resulted in a fuck ton of cat-fighting. I'm closing this.

**Comment by HIDEN64** [comment]
I'd also like to add, that *would* be an issue for people on macOS/other *nix OSes. This would cause them to also report as Linux, which I do not want.

**Pull request closed without merging**
